env:
  browser: true
  es2021: true
extends:
  - airbnb-typescript/base
  - import
  - standard-with-typescript
  - prettier
ignorePatterns:
  - 'dist/**/*.js'
  - 'dist/**/*.ts'
  - 'jest.config.ts'
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - prettier
rules:
  import/no-unresolved: error
  prettier/prettier: error
settings:
  import/parsers:
    "@typescript-eslint/parser":
    - ".ts"
    - ".tsx"
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
      - ./tsconfig.json