env:
  browser: true
  es2021: true
extends:
  - airbnb-typescript/base
  - standard-with-typescript
  - prettier
  - plugin:import/recommended
ignorePatterns:
  - 'dist/**/*.js'
  - 'dist/**/*.ts'
  - 'jest.config.ts'
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - prettier
rules:
  '@typescript-eslint/no-explicit-any': error
  import/no-unresolved: error
  prettier/prettier: error
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - ./tsconfig.json
